### PR TITLE
Add albums tree method

### PR DESCRIPTION
**Pull request by engineerjoe440**
Hi there, @Chostakovitch!

It's been a while. I'm still using this project quite a bit for the youth photo upload tool that I've been working on. I recently discovered that there's some need for access to the `/Albums::tree` API endpoint (which is undocumented, but clearly available, here: https://github.com/LycheeOrg/Lychee/blob/master/routes/api.php#L28).

This pull request should add that, and it should also help to add to the `pyproject.toml` file that will help to add some of the generics (to make it easier to publish to PyPI.org). I hope this will help. Please let me know if you have additional questions, I'd be very happy to add more or adjust as you see fit!

### CODE REVIEW

**Comment by Chostakovitch** [comment]
Wonderful, thanks @engineerjoe440 ! Just one little question: is the information within `pyproject.toml` redundant with `setup.cfg` ? If so, should I remove the `[metadata]` section in the later ?

**Comment by engineerjoe440** [comment]
> 

Actually, I think you're right. It probably would make those attributes a bit moot. If you're open to it, I can remove them as part of this Pull Request. 😃 

Thank you! Excited to get to offer a (small) contribution to the work I'm using so much!

**Comment by Chostakovitch** [comment]
> If you're open to it, I can remove them as part of this Pull Request

Absolutely ! :smile:

**Comment by engineerjoe440** [comment]
Thanks again, @Chostakovitch! Just pushed those changes to my working branch, this PR should now be up-to-date. 🎉

**Pull request merged**
