### PR TITLE
Documentation Updates and Cleanup

### PR DESCRIPTION
**Pull request by engineerjoe440**
## Purpose
This PR adds a link to the actual API documentation from the index page, it also modifies the index page to use the README.md document directly in the documentation to help keep things "in sync."

### CODE REVIEW

**Comment by engineerjoe440** [comment]
I should also say, I'm getting pretty close to the opportunity where I can actually start using this package in some project work (can't wait). I'll be sure to share some links with you to the development of that project when it comes along! :smile:

**Comment by Chostakovitch** [comment]
Great, thanks you ! Hope this project will be useful and functional - please report any bug or suboptimal stuff :)

**Comment by engineerjoe440** [comment]
Thank you @Chostakovitch! I certainly will report anything I find. The tool I'm going to be working on is a very simple photo-uploader tool for a youth conference. I'm actually working with one of the youth responsible for planning the conference to develop the tool, so it's serving as a learning opportunity for them. If it's ok with you, I might try to add to the docstrings for the various methods to include some example code snippets that will auto-render for the documentation, since it will be helpful for the youth to see code-samples to aid with learning. I'll do that in my own fork of the repo, and if it sounds at all helpful, I'll open a PR when we get started with that!

**Shameless plug:**
I need to do a little more writing on the subject, but I'm trying to blog/document the process as we go to share successes and failures about the development/learning process with the youth involved. The first article is here: https://blog.stanleysolutionsnw.com/reactjs-python-pictures-and-4h.html

Thank you again for starting this project! It's very exciting! :)

**Comment by Chostakovitch** [comment]
Hey @engineerjoe440, thanks for sharing your blog post ! I was not familiar with "teen conferences" (although I think there might be an equivalent in France - there is a national "party science" hosted by local universities with workshops and presentations for a few days...).

The interface to drop photos is really cool, especially with the Lychee backend for easy visualization, and hey, keeping control on our data, too. Great project! Even greater to do it with the youth. Obv your PR will be welcome! I'll read your next articles. :)

**Pull request merged**
